voltage_stacking_circuit_simulator: voltage_stacking_circuit_simulator.cc
	g++ voltage_stacking_circuit_simulator.cc GetSMPower.cc -ldl -o voltage_stacking_circuit_simulator -lrt

clean:
	-rm -f *.o voltage_stacking_circuit_simulator
